[package]
name = "pong"
version = "0.1.0"
edition = "2021"

[dependencies]
godot = "0.5.5"

[lib]
crate-type = ["cdylib"]

[features]
# Ensure that enabling `nothreads` for the main crate also enables
# that feature for other crates.
wasm = ["godot/experimental-wasm", "godot/lazy-function-tables"]
# Markers
nothreads = []
threads = []

wasm-nothreads = ["wasm", "nothreads", "godot/experimental-wasm-nothreads"]
